# Config
permalink: pretty
markdown: kramdown
sass:
  style: compressed
exclude:
  - Makefile
  - .idea
  - .git

# Setup
title: KSurf
url: https://www.ksurf.se
baseurl: ""

languages:
  - sv
  - en

nav:
  - home
#  - news
  - activities
  - contact
  - camps
#  - store
#  - partners

contact:
  street_address: Skanörs hamn
  locality: Vellinge
  postal_code: 239 30
  country_name: Sverige

  tel: 076 082 53 91
  email: '&#105;&#110;&#102;&#111;&#064;&#107;&#115;&#117;&#114;&#102;&#046;&#115;&#101;'
  url: https://www.ksurf.se

  facebook_url: https://www.facebook.com/ksurf.se
  instagram_url: https://www.instagram.com/ksurf.se/

en: &DEFAULT_I18N

  buttons:
    learn_more: learn more
    info_pricing: info & pricing
    request_booking: get in touch
    request_booking_short: get in touch

  booking_form:
    heading: I am interested
    cancel: Cancel
    close: Close
    send: Send request
    thank_you: |
      <strong>Thank you!</strong><br/>
      We'll get in touch as soon as possible.

    name:
      label: Your name
    email:
      label: E-mail
    phone:
      label: Phone
    lessons:
      label: Lessons
    package:
      label: Package
    start_date:
      label: Desired start date
    participants:
      label: Participants
    special_requests:
      label: Special requests


sv:
  <<: *DEFAULT_I18N

  buttons:
    learn_more: läs mer
    info_pricing: info & priser
    request_booking: intresseanmälan
    request_booking_short: intresse-<br/>anmälan

  booking_form:
    heading: Intresseanmälan
    cancel: Avbryt
    close: Stäng
    send: Skicka förfrågan
    thank_you: |
      <strong>Tusen tack!</strong><br/>
      Vi hör av oss så fort vi kan.

    name:
      label: Ditt namn
    email:
      label: E-mail
    phone:
      label: Mobil
    lessons:
      label: Lektioner
    package:
      label: Paket
    start_date:
      label: Önskat startdatum
    participants:
      label: Deltagare
    special_requests:
      label: Önskemål


fb_posts:
  - https://www.facebook.com/ksurf.se/posts/1754096081282716
  - https://www.facebook.com/ksurf.se/posts/1749800888378902
  - https://www.facebook.com/ksurf.se/posts/1747142785311379