# Config
permalink: pretty
markdown: kramdown
sass:
  style: compressed
exclude:
  - Makefile


# Setup
title: KSurf
url: https://www.ksurf.se
baseurl: ""

languages:
  - sv
  - en

nav:
  - news
  - activities
  - contact
#  - trips
#  - store
#  - partners

contact:
  street_address: Skanörs hamn
  locality: Vellinge
  postal_code: 239 30
  country_name: Sverige

  tel: 076 082 53 91
  email: '&#105;&#110;&#102;&#111;&#064;&#107;&#115;&#117;&#114;&#102;&#046;&#115;&#101;'
  url: https://www.ksurf.se

  facebook_url: https://www.facebook.com/ksurf.se
  instagram_url: https://www.instagram.com/ksurf.se/
